export const APP_ACCESS_PAGES = [
  { key: "home", label: "Inicio", category: "Portal", path: "/", patterns: ["/", "/inove", "/portal"] },
  { key: "inicio_rapido", label: "Inicio Rapido", category: "Portal", path: "/inicio-rapido", patterns: ["/inicio-rapido"] },
  { key: "painel", label: "Painel Executivo", category: "Portal", path: "/painel", patterns: ["/painel"] },

  { key: "tratativas_resumo", label: "Tratativas Resumo", category: "Tratativas", path: "/tratativas-resumo", patterns: ["/tratativas-resumo"] },
  { key: "tratativas_solicitacao", label: "Tratativas Solicitacao", category: "Tratativas", path: "/solicitar", patterns: ["/solicitar"] },
  { key: "tratativas_central", label: "Tratativas Central", category: "Tratativas", path: "/central", patterns: ["/central"] },
  { key: "tratativas_consultar", label: "Tratativas Consultar", category: "Tratativas", path: "/consultar/:id", patterns: ["/consultar/:id"] },
  { key: "tratativas_tratar", label: "Tratativas Tratar", category: "Tratativas", path: "/tratar/:id", patterns: ["/tratar/:id"] },
  { key: "tratativas_rh", label: "Tratativas RH", category: "Tratativas", path: "/tratativas-rh", patterns: ["/tratativas-rh"] },

  { key: "sac_resumo", label: "SAC Resumo", category: "SAC", path: "/sac/resumo", patterns: ["/sac/resumo"] },
  { key: "sac_lancamento", label: "SAC Lancamento", category: "SAC", path: "/sac/lancamento", patterns: ["/sac/lancamento"] },
  { key: "sac_central", label: "SAC Central", category: "SAC", path: "/sac/central", patterns: ["/sac", "/sac/central"] },

  { key: "avarias_lancamento", label: "Avarias Lancamento", category: "Avarias", path: "/lancar-avaria", patterns: ["/lancar-avaria"] },
  { key: "avarias_aprovacao", label: "Avarias Aprovacoes", category: "Avarias", path: "/aprovar-avarias", patterns: ["/aprovar-avarias"] },
  { key: "avarias_revisao", label: "Avarias Em Revisao", category: "Avarias", path: "/avarias-em-revisao", patterns: ["/avarias-em-revisao"] },
  { key: "avarias_cobrancas", label: "Avarias Cobrancas", category: "Avarias", path: "/cobrancas", patterns: ["/cobrancas"] },
  { key: "avarias_resumo", label: "Avarias Resumo", category: "Avarias", path: "/avarias-resumo", patterns: ["/avarias-resumo"] },

  { key: "acidentes_lancamento", label: "Acidentes Lancamento", category: "Acidentes", path: "/acidentes/lancamento", patterns: ["/acidentes/lancamento"] },
  { key: "acidentes_imagens", label: "Acidentes Imagens", category: "Acidentes", path: "/acidentes/imagens", patterns: ["/acidentes/imagens"] },
  { key: "acidentes_central", label: "Acidentes Central", category: "Acidentes", path: "/acidentes/central", patterns: ["/acidentes", "/acidentes/central"] },

  { key: "especial_lancamento", label: "Especial Lancamento", category: "Controle de Especial", path: "/controle-especial/lancamento", patterns: ["/controle-especial/lancamento"] },
  { key: "especial_central", label: "Especial Central", category: "Controle de Especial", path: "/controle-especial/central", patterns: ["/controle-especial", "/controle-especial/central"] },

  { key: "sos_solicitacao", label: "SOS Solicitacao", category: "Intervencoes", path: "/sos-solicitacao", patterns: ["/sos-solicitacao"] },
  { key: "sos_fechamento", label: "SOS Fechamento", category: "Intervencoes", path: "/sos-fechamento", patterns: ["/sos-fechamento"] },
  { key: "sos_tratamento", label: "SOS Manutencao", category: "Intervencoes", path: "/sos-tratamento", patterns: ["/sos-tratamento"] },
  { key: "sos_central", label: "SOS Central", category: "Intervencoes", path: "/sos-central", patterns: ["/sos-central"] },
  { key: "sos_dashboard", label: "SOS Dashboard", category: "Intervencoes", path: "/sos-dashboard", patterns: ["/sos-dashboard"] },
  { key: "sos_resumo", label: "SOS Resumo", category: "Intervencoes", path: "/sos-resumo", patterns: ["/sos-resumo"] },
  { key: "km_rodado", label: "KM Rodado", category: "Intervencoes", path: "/km-rodado", patterns: ["/km-rodado"] },

  { key: "pcm_inicio", label: "PCM Inicio", category: "PCM", path: "/pcm-inicio", patterns: ["/pcm-inicio"] },
  { key: "pcm_resumo", label: "PCM Resumo", category: "PCM", path: "/pcm-resumo", patterns: ["/pcm-resumo"] },
  { key: "pcm_diario", label: "PCM Diario", category: "PCM", path: "/pcm-diario/:id", patterns: ["/pcm-diario/:id"] },
  { key: "pcm_preventivas", label: "PCM Preventivas", category: "PCM", path: "/pcm-preventivas", patterns: ["/pcm-preventivas"] },
  { key: "pcm_troca_pneus", label: "PCM Troca de Pneus", category: "PCM", path: "/pcm-troca-pneus", patterns: ["/pcm-troca-pneus"] },
  { key: "pcm_controle_fichas", label: "PCM Controle de Fichas", category: "PCM", path: "/pcm-controle-fichas", patterns: ["/pcm-controle-fichas"] },
  { key: "pcm_controle_pneus", label: "PCM Controle de Pneus", category: "PCM", path: "/pcm-controle-pneus", patterns: ["/pcm-controle-pneus"] },

  { key: "checklists_central", label: "Checklists Central", category: "Checklists", path: "/checklists", patterns: ["/checklists"] },
  { key: "checklists_painel_sr", label: "Painel SR", category: "Checklists", path: "/checklists/painel-sr", patterns: ["/checklists/painel-sr"] },
  { key: "checklists_fichas_sr_manutencao", label: "Fichas SR - Manutenção", category: "Checklists", path: "/checklists/fichas-sr-manutencao", patterns: ["/checklists/fichas-sr-manutencao"] },

  { key: "embarcados_central", label: "Embarcados Central", category: "Embarcados", path: "/embarcados-central", patterns: ["/embarcados-central", "/embarcados"] },
  { key: "embarcados_movimentacoes", label: "Embarcados Movimentacoes", category: "Embarcados", path: "/embarcados-movimentacoes", patterns: ["/embarcados-movimentacoes"] },
  { key: "embarcados_reparos", label: "Embarcados Reparos", category: "Embarcados", path: "/embarcados-reparos", patterns: ["/embarcados-reparos"] },
  { key: "embarcados_reparo_detalhe", label: "Embarcados Reparo Detalhe", category: "Embarcados", path: "/embarcados-reparos/:id", patterns: ["/embarcados-reparos/:id"] },
  { key: "embarcados_reparo_execucao", label: "Embarcados Reparo Execucao", category: "Embarcados", path: "/embarcados-reparos/:id/executar", patterns: ["/embarcados-reparos/:id/executar"] },
  { key: "embarcados_envio_manutencao", label: "Embarcados Envio Manutencao", category: "Embarcados", path: "/embarcados-envio-manutencao", patterns: ["/embarcados-envio-manutencao"] },

  { key: "diesel_lancamento", label: "Diesel Lancamento Manual", category: "Desempenho Diesel", path: "/desempenho-lancamento", patterns: ["/desempenho-lancamento"] },
  { key: "diesel_resumo", label: "Diesel Resumo", category: "Desempenho Diesel", path: "/desempenho-diesel-resumo", patterns: ["/desempenho-diesel-resumo", "/desempenho-diesel"] },
  { key: "diesel_acompanhamento", label: "Diesel Acompanhamento", category: "Desempenho Diesel", path: "/desempenho-diesel-acompanhamento", patterns: ["/desempenho-diesel-acompanhamento"] },
  { key: "diesel_tratativas_legacy", label: "Diesel Tratativas Legado", category: "Desempenho Diesel", path: "/desempenho-diesel-tratativas", patterns: ["/desempenho-diesel-tratativas"] },
  { key: "diesel_agente", label: "Diesel Agente", category: "Desempenho Diesel", path: "/desempenho-diesel-agente", patterns: ["/desempenho-diesel-agente"] },
  { key: "diesel_checkpoint", label: "Diesel Checkpoint", category: "Desempenho Diesel", path: "/desempenho-diesel-checkpoint/:id", patterns: ["/desempenho-diesel-checkpoint/:id"] },
  { key: "diesel_tratativas_central", label: "Diesel Tratativas Central", category: "Desempenho Diesel", path: "/diesel-tratativas", patterns: ["/diesel-tratativas"] },
  { key: "diesel_tratativas_tratar", label: "Diesel Tratativas Tratar", category: "Desempenho Diesel", path: "/diesel-tratar/:id", patterns: ["/diesel-tratar/:id"] },
  { key: "diesel_tratativas_consultar", label: "Diesel Tratativas Consultar", category: "Desempenho Diesel", path: "/diesel-consultar/:id", patterns: ["/diesel-consultar/:id"] },

  { key: "estoque_diesel_resumo", label: "Medicao de Diesel", category: "Estoque de Diesel", path: "/estoque-diesel/resumo", patterns: ["/estoque-diesel/resumo", "/estoque-diesel", "/estoque-diesel/operacao", "/estoque-diesel/operacao/:ano/:mes"] },
  { key: "estoque_diesel_operacao", label: "Medicao Mensal de Diesel", category: "Estoque de Diesel", path: "/estoque-diesel/operacao/:ano/:mes", patterns: ["/estoque-diesel/operacao", "/estoque-diesel/operacao/:ano/:mes"] },
  { key: "estoque_diesel_planejamento_controle", label: "Programacao de Diesel", category: "Estoque de Diesel", path: "/estoque-diesel/programacao", patterns: ["/estoque-diesel/programacao", "/estoque-diesel/programacao/:ano/:mes", "/estoque-diesel/planejamento-controle"] },
  { key: "estoque_diesel_parametros", label: "Parametros de Diesel", category: "Estoque de Diesel", path: "/estoque-diesel/parametros", patterns: ["/estoque-diesel/parametros"] },

  { key: "suprimentos_resumo", label: "Suprimentos Resumo", category: "Suprimentos", path: "/suprimentos/resumo", patterns: ["/suprimentos/resumo", "/suprimentos"] },
  { key: "suprimentos_cadastro", label: "Suprimentos Cadastro", category: "Suprimentos", path: "/suprimentos/cadastro", patterns: ["/suprimentos/cadastro"] },
  { key: "suprimentos_garantias", label: "Suprimentos Garantias", category: "Suprimentos", path: "/suprimentos/garantias", patterns: ["/suprimentos/garantias"] },
  { key: "suprimentos_testes", label: "Suprimentos Testes", category: "Suprimentos", path: "/suprimentos/testes", patterns: ["/suprimentos/testes"] },
  { key: "suprimentos_servico_externo", label: "Suprimentos Servico Externo", category: "Suprimentos", path: "/suprimentos/servico-externo", patterns: ["/suprimentos/servico-externo"] },
  { key: "suprimentos_contagem", label: "Suprimentos Contagem", category: "Suprimentos", path: "/suprimentos/contagem", patterns: ["/suprimentos/contagem", "/suprimentos/contagem/dia/:data", "/suprimentos/contagem/lote/:loteId", "/suprimentos/contagem/semanal/:id"] },

  { key: "estrutura_fisica_solicitacao", label: "Estrutura Fisica Solicitacao", category: "Estrutura Fisica", path: "/estrutura-fisica/solicitacao", patterns: ["/estrutura-fisica/solicitacao"] },
  { key: "estrutura_fisica_central", label: "Estrutura Fisica Central", category: "Estrutura Fisica", path: "/estrutura-fisica/central", patterns: ["/estrutura-fisica/central", "/estrutura-fisica"] },
  { key: "estrutura_fisica_consultar", label: "Estrutura Fisica Consultar", category: "Estrutura Fisica", path: "/estrutura-fisica/consultar/:id", patterns: ["/estrutura-fisica/consultar/:id"] },
  { key: "estrutura_fisica_tratar", label: "Estrutura Fisica Tratar", category: "Estrutura Fisica", path: "/estrutura-fisica/tratar/:id", patterns: ["/estrutura-fisica/tratar/:id"] },

  { key: "config_usuarios", label: "Configuracoes Usuarios", category: "Configuracoes", path: "/usuarios", patterns: ["/usuarios"] },
  { key: "pessoas_funcionarios", label: "Funcionarios", category: "Pessoas", path: "/funcionarios", patterns: ["/funcionarios"] },
  { key: "pessoas_ferias", label: "Ferias", category: "Pessoas", path: "/ferias", patterns: ["/ferias"] },
  { key: "pessoas_organograma", label: "Organograma", category: "Pessoas", path: "/organograma", patterns: ["/organograma", "/organograma-canvas", "/organograma-manutencao"] },
  { key: "pessoas_vagas", label: "Vagas", category: "Pessoas", path: "/vagas", patterns: ["/vagas"] },
  { key: "config_niveis", label: "Configuracoes Niveis", category: "Configuracoes", path: "/niveis-acesso", patterns: ["/niveis-acesso"] },
  { key: "config_controle_dados", label: "Controle de Dados", category: "Configuracoes", path: "/controle-dados", patterns: ["/controle-dados"] },
  { key: "monitoramento", label: "Monitoramento Vision", category: "Monitoramento", path: "/monitoramento", patterns: ["/monitoramento", "/monitoramento/:id"] },
];

export const MOBILE_NAV_PRIORITY = [
  "home",
  "painel",
  "tratativas_central",
  "sac_central",
  "sac_lancamento",
  "avarias_resumo",
  "avarias_cobrancas",
  "acidentes_central",
  "acidentes_lancamento",
  "sos_resumo",
  "sos_solicitacao",
  "km_rodado",
  "diesel_resumo",
  "estoque_diesel_resumo",
  "embarcados_central",
  "embarcados_movimentacoes",
  "embarcados_reparos",
  "suprimentos_contagem",
  "pcm_resumo",
  "pcm_controle_pneus",
  "pcm_troca_pneus",
  "pcm_controle_fichas",
];

export const MOBILE_QUICK_LINK_PRIORITY = [
  "painel",
  "tratativas_central",
  "tratativas_resumo",
  "sac_central",
  "sac_resumo",
  "avarias_resumo",
  "avarias_cobrancas",
  "acidentes_central",
  "acidentes_lancamento",
  "sos_resumo",
  "sos_solicitacao",
  "km_rodado",
  "diesel_resumo",
  "estoque_diesel_resumo",
  "embarcados_central",
  "embarcados_movimentacoes",
  "embarcados_reparos",
  "suprimentos_contagem",
  "pcm_resumo",
  "pcm_controle_pneus",
  "pcm_troca_pneus",
  "pcm_controle_fichas",
];

export const DEFAULT_LEVEL_PROFILES = [
  {
    nome: "Pendente",
    descricao: "Aguardando configuracao de acesso.",
    ativo: true,
    paginas: [],
    farol_liberado: false,
  },
  {
    nome: "CCO",
    descricao: "Operacao e atendimento SOS.",
    ativo: true,
    paginas: ["inicio_rapido", "tratativas_solicitacao", "sac_lancamento", "sac_central", "acidentes_lancamento", "acidentes_central", "sos_solicitacao", "sos_fechamento", "sos_dashboard", "km_rodado", "embarcados_reparos"],
    farol_liberado: false,
  },
  {
    nome: "Manutenção",
    descricao: "Rotinas de manutencao, SOS, avarias e PCM.",
    ativo: true,
    paginas: [
      "inicio_rapido",
      "tratativas_solicitacao",
      "avarias_lancamento",
      "avarias_revisao",
      "avarias_aprovacao",
      "acidentes_lancamento",
      "acidentes_imagens",
      "acidentes_central",
      "sos_resumo",
      "sos_fechamento",
      "sos_tratamento",
      "sos_central",
      "sos_dashboard",
      "km_rodado",
      "pcm_resumo",
      "pcm_inicio",
      "pcm_diario",
      "pcm_preventivas",
      "pcm_controle_pneus",
      "pcm_troca_pneus",
      "pcm_controle_fichas",
      "embarcados_central",
      "embarcados_movimentacoes",
      "embarcados_reparos",
      "embarcados_reparo_detalhe",
      "embarcados_reparo_execucao",
      "suprimentos_resumo",
      "suprimentos_cadastro",
      "suprimentos_garantias",
      "suprimentos_testes",
      "suprimentos_servico_externo",
      "suprimentos_contagem",
      "pessoas_funcionarios",
      "pessoas_ferias",
      "pessoas_organograma",
    ],
    farol_liberado: false,
  },
  {
    nome: "Tratativa",
    descricao: "Central de tratativas e cobrancas.",
    ativo: true,
    paginas: ["inicio_rapido", "tratativas_solicitacao", "tratativas_central", "tratativas_consultar", "tratativas_tratar", "sac_resumo", "sac_lancamento", "sac_central", "avarias_cobrancas", "acidentes_imagens", "acidentes_central", "embarcados_reparos", "embarcados_reparo_detalhe", "embarcados_reparo_execucao"],
    farol_liberado: false,
  },
  {
    nome: "Instrutor",
    descricao: "Acompanhamento e tratativas do Diesel.",
    ativo: true,
    paginas: [
      "inicio_rapido",
      "diesel_lancamento",
      "diesel_resumo",
      "diesel_acompanhamento",
      "diesel_agente",
      "diesel_checkpoint",
      "diesel_tratativas_central",
      "diesel_tratativas_tratar",
      "diesel_tratativas_consultar",
      "estoque_diesel_resumo",
      "estoque_diesel_operacao",
      "estoque_diesel_planejamento_controle",
      "estoque_diesel_parametros",
    ],
    farol_liberado: false,
  },
  {
    nome: "Embarcados",
    descricao: "Operacao do modulo de embarcados.",
    ativo: true,
    paginas: [
      "inicio_rapido",
      "embarcados_central",
      "embarcados_movimentacoes",
      "embarcados_reparos",
      "embarcados_reparo_detalhe",
      "embarcados_reparo_execucao",
    ],
    farol_liberado: false,
  },
  {
    nome: "Borracheiro",
    descricao: "Troca de pneus.",
    ativo: true,
    paginas: ["pcm_troca_pneus", "pcm_controle_pneus"],
    farol_liberado: false,
  },
  {
    nome: "RH",
    descricao: "Tratativas RH e visao resumida.",
    ativo: true,
    paginas: ["home", "tratativas_resumo", "tratativas_central", "tratativas_consultar", "tratativas_rh", "sac_resumo", "sac_lancamento", "sac_central", "avarias_resumo", "avarias_cobrancas", "acidentes_imagens", "acidentes_central", "diesel_tratativas_central", "estrutura_fisica_solicitacao", "estrutura_fisica_central", "pessoas_funcionarios", "pessoas_ferias", "pessoas_organograma"],
    farol_liberado: true,
  },
  {
    nome: "Gestor",
    descricao: "Gestao operacional ampliada.",
    ativo: true,
    paginas: APP_ACCESS_PAGES.map((page) => page.key).filter((key) => key !== "config_niveis"),
    farol_liberado: true,
  },
  {
    nome: "Administrador",
    descricao: "Controle total do sistema.",
    ativo: true,
    paginas: APP_ACCESS_PAGES.map((page) => page.key),
    farol_liberado: true,
  },
];
