export const APP_ACCESS_PAGES = [
  { key: "home", label: "Inicio", category: "Portal", path: "/", patterns: ["/", "/inove", "/portal"] },
  { key: "inicio_rapido", label: "Inicio Rapido", category: "Portal", path: "/inicio-rapido", patterns: ["/inicio-rapido"] },
  { key: "painel", label: "Painel Executivo", category: "Portal", path: "/painel", patterns: ["/painel"] },

  { key: "tratativas_resumo", label: "Tratativas Resumo", category: "Tratativas", path: "/tratativas-resumo", patterns: ["/tratativas-resumo"] },
  { key: "tratativas_solicitacao", label: "Tratativas Solicitacao", category: "Tratativas", path: "/solicitar", patterns: ["/solicitar"] },
  { key: "tratativas_central", label: "Tratativas Central", category: "Tratativas", path: "/central", patterns: ["/central"] },
  { key: "tratativas_consultar", label: "Tratativas Consultar", category: "Tratativas", path: "/consultar/:id", patterns: ["/consultar/:id"] },
  { key: "tratativas_tratar", label: "Tratativas Tratar", category: "Tratativas", path: "/tratar/:id", patterns: ["/tratar/:id"] },
  { key: "tratativas_rh", label: "Tratativas RH", category: "Tratativas", path: "/tratativas-rh", patterns: ["/tratativas-rh"] },

  { key: "avarias_lancamento", label: "Avarias Lancamento", category: "Avarias", path: "/lancar-avaria", patterns: ["/lancar-avaria"] },
  { key: "avarias_aprovacao", label: "Avarias Aprovacoes", category: "Avarias", path: "/aprovar-avarias", patterns: ["/aprovar-avarias"] },
  { key: "avarias_revisao", label: "Avarias Em Revisao", category: "Avarias", path: "/avarias-em-revisao", patterns: ["/avarias-em-revisao"] },
  { key: "avarias_cobrancas", label: "Avarias Cobrancas", category: "Avarias", path: "/cobrancas", patterns: ["/cobrancas"] },
  { key: "avarias_resumo", label: "Avarias Resumo", category: "Avarias", path: "/avarias-resumo", patterns: ["/avarias-resumo"] },

  { key: "sos_solicitacao", label: "SOS Solicitacao", category: "Intervencoes", path: "/sos-solicitacao", patterns: ["/sos-solicitacao"] },
  { key: "sos_fechamento", label: "SOS Fechamento", category: "Intervencoes", path: "/sos-fechamento", patterns: ["/sos-fechamento"] },
  { key: "sos_tratamento", label: "SOS Manutencao", category: "Intervencoes", path: "/sos-tratamento", patterns: ["/sos-tratamento"] },
  { key: "sos_central", label: "SOS Central", category: "Intervencoes", path: "/sos-central", patterns: ["/sos-central"] },
  { key: "sos_dashboard", label: "SOS Dashboard", category: "Intervencoes", path: "/sos-dashboard", patterns: ["/sos-dashboard"] },
  { key: "sos_resumo", label: "SOS Resumo", category: "Intervencoes", path: "/sos-resumo", patterns: ["/sos-resumo"] },
  { key: "km_rodado", label: "KM Rodado", category: "Intervencoes", path: "/km-rodado", patterns: ["/km-rodado"] },

  { key: "pcm_inicio", label: "PCM Inicio", category: "PCM", path: "/pcm-inicio", patterns: ["/pcm-inicio"] },
  { key: "pcm_resumo", label: "PCM Resumo", category: "PCM", path: "/pcm-resumo", patterns: ["/pcm-resumo"] },
  { key: "pcm_diario", label: "PCM Diario", category: "PCM", path: "/pcm-diario/:id", patterns: ["/pcm-diario/:id"] },
  { key: "pcm_preventivas", label: "PCM Preventivas", category: "PCM", path: "/pcm-preventivas", patterns: ["/pcm-preventivas"] },
  { key: "pcm_troca_pneus", label: "PCM Troca de Pneus", category: "PCM", path: "/pcm-troca-pneus", patterns: ["/pcm-troca-pneus"] },

  { key: "checklists_central", label: "Checklists Central", category: "Checklists", path: "/checklists", patterns: ["/checklists"] },

  { key: "embarcados_central", label: "Embarcados Central", category: "Embarcados", path: "/embarcados-central", patterns: ["/embarcados-central", "/embarcados"] },
  { key: "embarcados_movimentacoes", label: "Embarcados Movimentacoes", category: "Embarcados", path: "/embarcados-movimentacoes", patterns: ["/embarcados-movimentacoes"] },
  { key: "embarcados_reparos", label: "Embarcados Reparos", category: "Embarcados", path: "/embarcados-reparos", patterns: ["/embarcados-reparos"] },
  { key: "embarcados_reparo_detalhe", label: "Embarcados Reparo Detalhe", category: "Embarcados", path: "/embarcados-reparos/:id", patterns: ["/embarcados-reparos/:id"] },
  { key: "embarcados_reparo_execucao", label: "Embarcados Reparo Execucao", category: "Embarcados", path: "/embarcados-reparos/:id/executar", patterns: ["/embarcados-reparos/:id/executar"] },
  { key: "embarcados_envio_manutencao", label: "Embarcados Envio Manutencao", category: "Embarcados", path: "/embarcados-envio-manutencao", patterns: ["/embarcados-envio-manutencao"] },

  { key: "diesel_lancamento", label: "Diesel Lancamento Manual", category: "Desempenho Diesel", path: "/desempenho-lancamento", patterns: ["/desempenho-lancamento"] },
  { key: "diesel_resumo", label: "Diesel Resumo", category: "Desempenho Diesel", path: "/desempenho-diesel-resumo", patterns: ["/desempenho-diesel-resumo", "/desempenho-diesel"] },
  { key: "diesel_acompanhamento", label: "Diesel Acompanhamento", category: "Desempenho Diesel", path: "/desempenho-diesel-acompanhamento", patterns: ["/desempenho-diesel-acompanhamento"] },
  { key: "diesel_tratativas_legacy", label: "Diesel Tratativas Legado", category: "Desempenho Diesel", path: "/desempenho-diesel-tratativas", patterns: ["/desempenho-diesel-tratativas"] },
  { key: "diesel_agente", label: "Diesel Agente", category: "Desempenho Diesel", path: "/desempenho-diesel-agente", patterns: ["/desempenho-diesel-agente"] },
  { key: "diesel_checkpoint", label: "Diesel Checkpoint", category: "Desempenho Diesel", path: "/desempenho-diesel-checkpoint/:id", patterns: ["/desempenho-diesel-checkpoint/:id"] },
  { key: "diesel_tratativas_central", label: "Diesel Tratativas Central", category: "Desempenho Diesel", path: "/diesel-tratativas", patterns: ["/diesel-tratativas"] },
  { key: "diesel_tratativas_tratar", label: "Diesel Tratativas Tratar", category: "Desempenho Diesel", path: "/diesel-tratar/:id", patterns: ["/diesel-tratar/:id"] },
  { key: "diesel_tratativas_consultar", label: "Diesel Tratativas Consultar", category: "Desempenho Diesel", path: "/diesel-consultar/:id", patterns: ["/diesel-consultar/:id"] },

  { key: "estoque_diesel_resumo", label: "Medicao de Diesel", category: "Estoque de Diesel", path: "/estoque-diesel/resumo", patterns: ["/estoque-diesel/resumo", "/estoque-diesel", "/estoque-diesel/operacao", "/estoque-diesel/operacao/:ano/:mes"] },
  { key: "estoque_diesel_operacao", label: "Medicao Mensal de Diesel", category: "Estoque de Diesel", path: "/estoque-diesel/operacao/:ano/:mes", patterns: ["/estoque-diesel/operacao", "/estoque-diesel/operacao/:ano/:mes"] },
  { key: "estoque_diesel_planejamento_controle", label: "Programacao de Diesel", category: "Estoque de Diesel", path: "/estoque-diesel/programacao", patterns: ["/estoque-diesel/programacao", "/estoque-diesel/programacao/:ano/:mes", "/estoque-diesel/planejamento-controle"] },
  { key: "estoque_diesel_parametros", label: "Parametros de Diesel", category: "Estoque de Diesel", path: "/estoque-diesel/parametros", patterns: ["/estoque-diesel/parametros"] },

  { key: "estrutura_fisica_solicitacao", label: "Estrutura Fisica Solicitacao", category: "Estrutura Fisica", path: "/estrutura-fisica/solicitacao", patterns: ["/estrutura-fisica/solicitacao"] },
  { key: "estrutura_fisica_central", label: "Estrutura Fisica Central", category: "Estrutura Fisica", path: "/estrutura-fisica/central", patterns: ["/estrutura-fisica/central", "/estrutura-fisica"] },
  { key: "estrutura_fisica_consultar", label: "Estrutura Fisica Consultar", category: "Estrutura Fisica", path: "/estrutura-fisica/consultar/:id", patterns: ["/estrutura-fisica/consultar/:id"] },
  { key: "estrutura_fisica_tratar", label: "Estrutura Fisica Tratar", category: "Estrutura Fisica", path: "/estrutura-fisica/tratar/:id", patterns: ["/estrutura-fisica/tratar/:id"] },

  { key: "config_usuarios", label: "Configuracoes Usuarios", category: "Configuracoes", path: "/usuarios", patterns: ["/usuarios"] },
  { key: "config_funcionarios", label: "Configuracoes Funcionarios", category: "Configuracoes", path: "/funcionarios", patterns: ["/funcionarios"] },
  { key: "config_organograma_manutencao", label: "Configuracoes Organograma Manutencao", category: "Configuracoes", path: "/organograma-manutencao", patterns: ["/organograma-manutencao"] },
  { key: "config_niveis", label: "Configuracoes Niveis", category: "Configuracoes", path: "/niveis-acesso", patterns: ["/niveis-acesso"] },
];

export const MOBILE_NAV_PRIORITY = [
  "home",
  "painel",
  "tratativas_central",
  "avarias_resumo",
  "avarias_cobrancas",
  "sos_resumo",
  "sos_solicitacao",
  "km_rodado",
  "diesel_resumo",
  "estoque_diesel_resumo",
  "embarcados_central",
  "embarcados_reparos",
  "pcm_resumo",
  "pcm_troca_pneus",
];

export const MOBILE_QUICK_LINK_PRIORITY = [
  "painel",
  "tratativas_central",
  "tratativas_resumo",
  "avarias_resumo",
  "avarias_cobrancas",
  "sos_resumo",
  "sos_solicitacao",
  "km_rodado",
  "diesel_resumo",
  "estoque_diesel_resumo",
  "embarcados_central",
  "embarcados_reparos",
  "pcm_resumo",
  "pcm_troca_pneus",
];

export const DEFAULT_LEVEL_PROFILES = [
  {
    nome: "Pendente",
    descricao: "Aguardando configuracao de acesso.",
    ativo: true,
    paginas: [],
    farol_liberado: false,
  },
  {
    nome: "CCO",
    descricao: "Operacao e atendimento SOS.",
    ativo: true,
    paginas: ["inicio_rapido", "tratativas_solicitacao", "sos_solicitacao", "sos_fechamento", "sos_dashboard", "km_rodado", "embarcados_reparos"],
    farol_liberado: false,
  },
  {
    nome: "Manutenção",
    descricao: "Rotinas de manutencao, SOS, avarias e PCM.",
    ativo: true,
    paginas: [
      "inicio_rapido",
      "tratativas_solicitacao",
      "avarias_lancamento",
      "avarias_revisao",
      "avarias_aprovacao",
      "sos_resumo",
      "sos_fechamento",
      "sos_tratamento",
      "sos_central",
      "sos_dashboard",
      "km_rodado",
      "pcm_resumo",
      "pcm_inicio",
      "pcm_diario",
      "pcm_preventivas",
      "pcm_troca_pneus",
      "embarcados_central",
      "embarcados_movimentacoes",
      "embarcados_reparos",
      "embarcados_reparo_detalhe",
      "embarcados_reparo_execucao",
      "embarcados_envio_manutencao",
      "config_organograma_manutencao",
    ],
    farol_liberado: false,
  },
  {
    nome: "Tratativa",
    descricao: "Central de tratativas e cobrancas.",
    ativo: true,
    paginas: ["inicio_rapido", "tratativas_solicitacao", "tratativas_central", "tratativas_consultar", "tratativas_tratar", "avarias_cobrancas", "embarcados_reparos", "embarcados_reparo_detalhe", "embarcados_reparo_execucao"],
    farol_liberado: false,
  },
  {
    nome: "Instrutor",
    descricao: "Acompanhamento e tratativas do Diesel.",
    ativo: true,
    paginas: [
      "inicio_rapido",
      "diesel_lancamento",
      "diesel_resumo",
      "diesel_acompanhamento",
      "diesel_agente",
      "diesel_checkpoint",
      "diesel_tratativas_central",
      "diesel_tratativas_tratar",
      "diesel_tratativas_consultar",
      "estoque_diesel_resumo",
      "estoque_diesel_operacao",
      "estoque_diesel_planejamento_controle",
      "estoque_diesel_parametros",
    ],
    farol_liberado: false,
  },
  {
    nome: "Embarcados",
    descricao: "Operacao do modulo de embarcados.",
    ativo: true,
    paginas: [
      "inicio_rapido",
      "embarcados_central",
      "embarcados_movimentacoes",
      "embarcados_reparos",
      "embarcados_reparo_detalhe",
      "embarcados_reparo_execucao",
      "embarcados_envio_manutencao",
    ],
    farol_liberado: false,
  },
  {
    nome: "Borracheiro",
    descricao: "Troca de pneus.",
    ativo: true,
    paginas: ["pcm_troca_pneus"],
    farol_liberado: false,
  },
  {
    nome: "RH",
    descricao: "Tratativas RH e visao resumida.",
    ativo: true,
    paginas: ["home", "tratativas_resumo", "tratativas_central", "tratativas_consultar", "tratativas_rh", "avarias_resumo", "avarias_cobrancas", "diesel_tratativas_central", "estrutura_fisica_solicitacao", "estrutura_fisica_central", "config_organograma_manutencao"],
    farol_liberado: true,
  },
  {
    nome: "Gestor",
    descricao: "Gestao operacional ampliada.",
    ativo: true,
    paginas: APP_ACCESS_PAGES.map((page) => page.key).filter((key) => key !== "config_niveis"),
    farol_liberado: true,
  },
  {
    nome: "Administrador",
    descricao: "Controle total do sistema.",
    ativo: true,
    paginas: APP_ACCESS_PAGES.map((page) => page.key),
    farol_liberado: true,
  },
];
