const baseAreas = [
  {
    codigo: "ger_planejamento",
    parentCodigo: null,
    titulo: "Guilherme Maximo",
    subtitulo: "Gerente de Planejamento",
    tipo: "GESTAO",
    grupo: "Lideranca",
    turno: "DIURNA",
    cor: "stone",
    ordem: 10,
    detalhe: "Responsavel por planejamento, suprimentos e apoio operacional.",
    orcadoQtd: 1,
    realizadoQtd: 1,
  },
  {
    codigo: "planejamento_suprimentos",
    parentCodigo: "ger_planejamento",
    titulo: "Planejamento e Suprimentos",
    subtitulo: "Backoffice de apoio a manutencao",
    tipo: "SQUAD",
    grupo: "Planejamento e Suprimentos",
    turno: "DIURNA",
    cor: "emerald",
    ordem: 20,
    detalhe: "PCM, compras, almoxarifado e controle de entradas e saidas.",
    orcadoQtd: 0,
    realizadoQtd: 0,
  },
  {
    codigo: "entrada_saida",
    parentCodigo: "planejamento_suprimentos",
    titulo: "Entrada/Saida",
    subtitulo: "Fluxo de patio e oficina",
    tipo: "CELULA",
    grupo: "Planejamento e Suprimentos",
    turno: "DIURNA",
    cor: "emerald",
    ordem: 30,
    detalhe: "Recebe os veiculos e organiza a fila de manutencao.",
    orcadoQtd: 1,
    realizadoQtd: 1,
  },
  {
    codigo: "pcm",
    parentCodigo: "planejamento_suprimentos",
    titulo: "PCM",
    subtitulo: "Planejamento e programacao",
    tipo: "CELULA",
    grupo: "Planejamento e Suprimentos",
    turno: "DIURNA",
    cor: "emerald",
    ordem: 40,
    detalhe: "Planejamento, cadastro e controle do backlog.",
    orcadoQtd: 2,
    realizadoQtd: 2,
  },
  {
    codigo: "compras",
    parentCodigo: "planejamento_suprimentos",
    titulo: "Compras",
    subtitulo: "Suprimentos e contratos",
    tipo: "CELULA",
    grupo: "Planejamento e Suprimentos",
    turno: "DIURNA",
    cor: "emerald",
    ordem: 50,
    detalhe: "Compras tecnicas e apoio de fornecedores.",
    orcadoQtd: 2,
    realizadoQtd: 1,
  },
  {
    codigo: "almoxarifado",
    parentCodigo: "planejamento_suprimentos",
    titulo: "Almoxarifado",
    subtitulo: "Controle de estoque e entrega",
    tipo: "CELULA",
    grupo: "Planejamento e Suprimentos",
    turno: "DIURNA",
    cor: "emerald",
    ordem: 60,
    detalhe: "Recebimento, conferencia e distribuicao de itens.",
    orcadoQtd: 4,
    realizadoQtd: 3,
  },
  {
    codigo: "ger_manutencao",
    parentCodigo: null,
    titulo: "Fernando Oliveira",
    subtitulo: "Gerente de Manutencao",
    tipo: "GESTAO",
    grupo: "Lideranca",
    turno: "DIURNA",
    cor: "stone",
    ordem: 70,
    detalhe: "Responsavel pelas frentes preventiva, corretiva, inspecao e limpeza.",
    orcadoQtd: 1,
    realizadoQtd: 1,
  },
  {
    codigo: "equipe_preventiva",
    parentCodigo: "ger_manutencao",
    titulo: "Equipe Preventiva Parada 16:00",
    subtitulo: "Frente preventiva diurna",
    tipo: "SQUAD",
    grupo: "Equipe Preventiva",
    turno: "DIURNA",
    cor: "blue",
    ordem: 80,
    detalhe: "Linha dedicada a rotinas preventivas e revisoes.",
    orcadoQtd: 0,
    realizadoQtd: 0,
  },
  {
    codigo: "lavagem_prev",
    parentCodigo: "equipe_preventiva",
    titulo: "Lavagem",
    subtitulo: "Preparacao preventiva",
    tipo: "CELULA",
    grupo: "Equipe Preventiva",
    turno: "DIURNA",
    cor: "emerald",
    ordem: 90,
    detalhe: "Pre-lavagem e apoio visual para inspecoes.",
    orcadoQtd: 2,
    realizadoQtd: 1,
  },
  {
    codigo: "hidraulica_prev",
    parentCodigo: "equipe_preventiva",
    titulo: "Hidraulica",
    subtitulo: "Sistema hidraulico",
    tipo: "CELULA",
    grupo: "Equipe Preventiva",
    turno: "DIURNA",
    cor: "emerald",
    ordem: 100,
    detalhe: "Inspecao de linhas, atuadores e vazamentos.",
    orcadoQtd: 4,
    realizadoQtd: 3,
  },
  {
    codigo: "eletrica_prev",
    parentCodigo: "equipe_preventiva",
    titulo: "Eletrica",
    subtitulo: "Preventiva eletrica",
    tipo: "CELULA",
    grupo: "Equipe Preventiva",
    turno: "DIURNA",
    cor: "emerald",
    ordem: 110,
    detalhe: "Chicotes, sensores, scanner e ajustes finos.",
    orcadoQtd: 3,
    realizadoQtd: 2,
  },
  {
    codigo: "lanterneiro_prev",
    parentCodigo: "equipe_preventiva",
    titulo: "Lanterneiro",
    subtitulo: "Estrutura e acabamento",
    tipo: "CELULA",
    grupo: "Equipe Preventiva",
    turno: "DIURNA",
    cor: "emerald",
    ordem: 120,
    detalhe: "Inspecao de carroceria e pequenos reparos.",
    orcadoQtd: 2,
    realizadoQtd: 1,
  },
  {
    codigo: "borracheiro_prev",
    parentCodigo: "equipe_preventiva",
    titulo: "Borracheiro",
    subtitulo: "Pneus e rodas",
    tipo: "CELULA",
    grupo: "Equipe Preventiva",
    turno: "DIURNA",
    cor: "emerald",
    ordem: 130,
    detalhe: "Checklist de pneus, rodas e calibragem.",
    orcadoQtd: 2,
    realizadoQtd: 1,
  },
  {
    codigo: "equipe_corretiva",
    parentCodigo: "ger_manutencao",
    titulo: "Equipe Corretiva",
    subtitulo: "Atendimento diurno de corretivas",
    tipo: "SQUAD",
    grupo: "Equipe Corretiva",
    turno: "DIURNA",
    cor: "amber",
    ordem: 140,
    detalhe: "Frente de corretiva para mecanica, eletrica e apoio tecnico.",
    orcadoQtd: 0,
    realizadoQtd: 0,
  },
  {
    codigo: "mecanica_corretiva",
    parentCodigo: "equipe_corretiva",
    titulo: "Mecanica",
    subtitulo: "Corretiva mecanica",
    tipo: "CELULA",
    grupo: "Equipe Corretiva",
    turno: "DIURNA",
    cor: "emerald",
    ordem: 150,
    detalhe: "Motor, caixa, suspensao e freios.",
    orcadoQtd: 4,
    realizadoQtd: 3,
  },
  {
    codigo: "eletrica_corretiva",
    parentCodigo: "equipe_corretiva",
    titulo: "Eletrica",
    subtitulo: "Corretiva eletrica",
    tipo: "CELULA",
    grupo: "Equipe Corretiva",
    turno: "DIURNA",
    cor: "sky",
    ordem: 160,
    detalhe: "Diagnostico, painel, scanner e chicote.",
    orcadoQtd: 3,
    realizadoQtd: 2,
  },
  {
    codigo: "lanterneiro_corretiva",
    parentCodigo: "equipe_corretiva",
    titulo: "Lanterneiro",
    subtitulo: "Estrutura e solda",
    tipo: "CELULA",
    grupo: "Equipe Corretiva",
    turno: "DIURNA",
    cor: "emerald",
    ordem: 170,
    detalhe: "Estrutura, solda e acabamento corretivo.",
    orcadoQtd: 4,
    realizadoQtd: 3,
  },
  {
    codigo: "lavagem_corretiva",
    parentCodigo: "equipe_corretiva",
    titulo: "Lavagem",
    subtitulo: "Apoio de entrega",
    tipo: "CELULA",
    grupo: "Equipe Corretiva",
    turno: "DIURNA",
    cor: "emerald",
    ordem: 180,
    detalhe: "Lavagem tecnica para liberacao e inspecao final.",
    orcadoQtd: 3,
    realizadoQtd: 2,
  },
  {
    codigo: "mecanica_pesada",
    parentCodigo: "equipe_corretiva",
    titulo: "Mecanica Pesada",
    subtitulo: "Casos de maior complexidade",
    tipo: "CELULA",
    grupo: "Equipe Corretiva",
    turno: "DIURNA",
    cor: "emerald",
    ordem: 190,
    detalhe: "Falhas severas e desmontagens maiores.",
    orcadoQtd: 2,
    realizadoQtd: 2,
  },
  {
    codigo: "motor_corretiva",
    parentCodigo: "equipe_corretiva",
    titulo: "Motor",
    subtitulo: "Especialidade dedicada",
    tipo: "CELULA",
    grupo: "Equipe Corretiva",
    turno: "DIURNA",
    cor: "emerald",
    ordem: 200,
    detalhe: "Montagem, regulagem e testes de motor.",
    orcadoQtd: 2,
    realizadoQtd: 1,
  },
  {
    codigo: "equipe_inspecao",
    parentCodigo: "ger_manutencao",
    titulo: "Equipe Inspecao e 5S",
    subtitulo: "Confiabilidade e disciplina operacional",
    tipo: "SQUAD",
    grupo: "Equipe Inspecao e 5S",
    turno: "DIURNA",
    cor: "blue",
    ordem: 210,
    detalhe: "Inspecoes de padrao e manutencao de rotina.",
    orcadoQtd: 0,
    realizadoQtd: 0,
  },
  {
    codigo: "hidraulica_inspecao",
    parentCodigo: "equipe_inspecao",
    titulo: "Hidraulica",
    subtitulo: "Inspecao dedicada",
    tipo: "CELULA",
    grupo: "Equipe Inspecao e 5S",
    turno: "DIURNA",
    cor: "emerald",
    ordem: 220,
    detalhe: "Checagem rapida de sistemas criticos.",
    orcadoQtd: 2,
    realizadoQtd: 1,
  },
  {
    codigo: "equipe_melhorias",
    parentCodigo: "ger_manutencao",
    titulo: "Equipe Corretiva, Melhorias e Administrativo",
    subtitulo: "Apoio de suporte e melhorias",
    tipo: "SQUAD",
    grupo: "Equipe Melhorias",
    turno: "NOTURNA",
    cor: "amber",
    ordem: 230,
    detalhe: "Mistura frentes noturnas, administrativo e almoxarifado.",
    orcadoQtd: 0,
    realizadoQtd: 0,
  },
  {
    codigo: "mecanica_melhorias",
    parentCodigo: "equipe_melhorias",
    titulo: "Mecanica",
    subtitulo: "Melhorias e apoio",
    tipo: "CELULA",
    grupo: "Equipe Melhorias",
    turno: "NOTURNA",
    cor: "emerald",
    ordem: 240,
    detalhe: "Melhorias continuas e backlog noturno.",
    orcadoQtd: 3,
    realizadoQtd: 2,
  },
  {
    codigo: "eletrica_melhorias",
    parentCodigo: "equipe_melhorias",
    titulo: "Eletrica",
    subtitulo: "Apoio noturno",
    tipo: "CELULA",
    grupo: "Equipe Melhorias",
    turno: "NOTURNA",
    cor: "emerald",
    ordem: 250,
    detalhe: "Frente eletrica de apoio a corretivas e melhorias.",
    orcadoQtd: 2,
    realizadoQtd: 1,
  },
  {
    codigo: "almoxarife_melhorias",
    parentCodigo: "equipe_melhorias",
    titulo: "Almoxarife",
    subtitulo: "Suporte de materiais",
    tipo: "CELULA",
    grupo: "Equipe Melhorias",
    turno: "NOTURNA",
    cor: "emerald",
    ordem: 260,
    detalhe: "Separacao de itens para as frentes de manutencao.",
    orcadoQtd: 2,
    realizadoQtd: 1,
  },
  {
    codigo: "administrativo_melhorias",
    parentCodigo: "equipe_melhorias",
    titulo: "Administrativo",
    subtitulo: "Backoffice noturno",
    tipo: "CELULA",
    grupo: "Equipe Melhorias",
    turno: "NOTURNA",
    cor: "emerald",
    ordem: 270,
    detalhe: "Apoio documental e fechamento de demandas.",
    orcadoQtd: 1,
    realizadoQtd: 1,
  },
  {
    codigo: "equipe_limpeza",
    parentCodigo: "ger_manutencao",
    titulo: "Limpeza",
    subtitulo: "Equipe de patio e oficina",
    tipo: "SQUAD",
    grupo: "Limpeza",
    turno: "NOTURNA",
    cor: "orange",
    ordem: 280,
    detalhe: "Mantem patio, boxes e veiculos em condicao de entrega.",
    orcadoQtd: 0,
    realizadoQtd: 0,
  },
  {
    codigo: "limpeza_box_a",
    parentCodigo: "equipe_limpeza",
    titulo: "Limpeza A",
    subtitulo: "Frente principal",
    tipo: "CELULA",
    grupo: "Limpeza",
    turno: "NOTURNA",
    cor: "orange",
    ordem: 290,
    detalhe: "Equipe de higienizacao da linha A.",
    orcadoQtd: 6,
    realizadoQtd: 5,
  },
  {
    codigo: "limpeza_box_b",
    parentCodigo: "equipe_limpeza",
    titulo: "Limpeza B",
    subtitulo: "Frente secundaria",
    tipo: "CELULA",
    grupo: "Limpeza",
    turno: "NOTURNA",
    cor: "orange",
    ordem: 300,
    detalhe: "Equipe de higienizacao da linha B.",
    orcadoQtd: 6,
    realizadoQtd: 4,
  },
];

const explicitRealizados = {
  ger_planejamento: [{ nome: "Guilherme Maximo", cargo: "Gerente de Planejamento" }],
  ger_manutencao: [{ nome: "Fernando Oliveira", cargo: "Gerente de Manutencao" }],
  pcm: [
    { nome: "Analista PCM 01", cargo: "PCM" },
    { nome: "Analista PCM 02", cargo: "PCM" },
  ],
  compras: [{ nome: "Comprador 01", cargo: "Compras" }],
  almoxarifado: [
    { nome: "Almoxarife 01", cargo: "Almoxarifado" },
    { nome: "Almoxarife 02", cargo: "Almoxarifado" },
    { nome: "Almoxarife 03", cargo: "Almoxarifado" },
  ],
};

function buildPeopleRowsFromCount(area, type, count) {
  const baseName = type === "ORCADO" ? "Vaga" : "Colaborador";
  return Array.from({ length: count }, (_, index) => ({
    areaCodigo: area.codigo,
    nome: `${area.titulo} ${baseName} ${String(index + 1).padStart(2, "0")}`,
    cargo: area.titulo,
    tipoHeadcount: type,
    turno: area.turno || null,
    status: type === "REALIZADO" ? "ATIVO" : "PLANEJADO",
    ordem: index + 1,
    chapa: "",
    telefone: "",
    observacao: area.detalhe || "",
  }));
}

function buildFallbackPeople(areas) {
  return areas.flatMap((area) => {
    const rows = [];
    const orcadoQtd = Number(area.orcadoQtd || 0);
    const realizadoQtd = Number(area.realizadoQtd || 0);

    if (orcadoQtd > 0) {
      rows.push(...buildPeopleRowsFromCount(area, "ORCADO", orcadoQtd));
    }

    const explicitRows = explicitRealizados[area.codigo] || [];
    if (explicitRows.length) {
      rows.push(
        ...explicitRows.map((item, index) => ({
          areaCodigo: area.codigo,
          nome: item.nome,
          cargo: item.cargo || area.titulo,
          tipoHeadcount: "REALIZADO",
          turno: area.turno || null,
          status: "ATIVO",
          ordem: index + 1,
          chapa: item.chapa || "",
          telefone: item.telefone || "",
          observacao: area.detalhe || "",
        }))
      );
    }

    if (realizadoQtd > explicitRows.length) {
      rows.push(
        ...buildPeopleRowsFromCount(area, "REALIZADO", realizadoQtd - explicitRows.length).map(
          (row, index) => ({
            ...row,
            ordem: explicitRows.length + index + 1,
          })
        )
      );
    }

    return rows;
  });
}

export const ORGANOGRAMA_FALLBACK_AREAS = baseAreas;
export const ORGANOGRAMA_FALLBACK_PESSOAS = buildFallbackPeople(baseAreas);
