create table if not exists public.acidentes_ocorrencias (
  id uuid primary key default gen_random_uuid(),
  numero_ocorrencia bigint generated by default as identity,
  status text not null default 'Aguardando imagens'
    check (status in ('Aguardando imagens', 'Em aberto', 'Concluido', 'Cancelado')),
  precisa_imagens boolean not null default true,

  data_ocorrencia date not null,
  hora_ocorrencia time not null,
  local text not null,
  linha text,
  prefixo text not null,
  motorista_chapa text,
  motorista_nome text,

  tipo_acidente text not null default 'Colisao com terceiro',
  veiculo_terceiro text,
  placa_terceiro text,
  condutor_terceiro text,
  telefone_terceiro text,
  descricao text not null,
  situacao_operacional text not null default 'Seguiu viagem'
    check (situacao_operacional in ('Seguiu viagem', 'Aguardando orientação', 'Recolhido para garagem')),

  dano_coletivo boolean not null default false,
  dano_terceiro boolean not null default true,
  registros_observacao text,
  mensagem_whatsapp text,
  evidencias_urls jsonb not null default '[]'::jsonb,

  imagens_analisadas_em timestamptz,
  imagens_analisadas_por text,
  imagens_confirmam_ocorrencia text,
  imagens_responsabilidade text,
  imagens_observacao text,
  imagens_urls jsonb not null default '[]'::jsonb,

  parecer_final text,
  cancelado_motivo text,
  concluido_em timestamptz,
  cancelado_em timestamptz,

  criado_por_login text,
  criado_por_nome text,
  criado_por_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.acidentes_tratativas (
  id uuid primary key default gen_random_uuid(),
  acidente_id uuid not null references public.acidentes_ocorrencias(id) on delete cascade,
  tipo text not null default 'Tratativa',
  descricao text not null,
  evidencias_urls jsonb not null default '[]'::jsonb,
  criado_por_login text,
  criado_por_nome text,
  criado_por_id text,
  created_at timestamptz not null default now()
);

create index if not exists acidentes_ocorrencias_status_idx
  on public.acidentes_ocorrencias (status);
create index if not exists acidentes_ocorrencias_data_idx
  on public.acidentes_ocorrencias (data_ocorrencia desc, hora_ocorrencia desc);
create index if not exists acidentes_ocorrencias_prefixo_idx
  on public.acidentes_ocorrencias (prefixo);
create index if not exists acidentes_ocorrencias_motorista_idx
  on public.acidentes_ocorrencias (motorista_chapa);
create index if not exists acidentes_tratativas_acidente_idx
  on public.acidentes_tratativas (acidente_id, created_at desc);

create or replace function public.acidentes_set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_acidentes_ocorrencias_updated_at on public.acidentes_ocorrencias;
create trigger trg_acidentes_ocorrencias_updated_at
before update on public.acidentes_ocorrencias
for each row
execute function public.acidentes_set_updated_at();

alter table public.acidentes_ocorrencias enable row level security;
alter table public.acidentes_tratativas enable row level security;

drop policy if exists "acidentes_ocorrencias_select_all" on public.acidentes_ocorrencias;
create policy "acidentes_ocorrencias_select_all"
  on public.acidentes_ocorrencias for select
  to authenticated using (true);

drop policy if exists "acidentes_ocorrencias_insert_all" on public.acidentes_ocorrencias;
create policy "acidentes_ocorrencias_insert_all"
  on public.acidentes_ocorrencias for insert
  to authenticated with check (true);

drop policy if exists "acidentes_ocorrencias_update_all" on public.acidentes_ocorrencias;
create policy "acidentes_ocorrencias_update_all"
  on public.acidentes_ocorrencias for update
  to authenticated using (true) with check (true);

drop policy if exists "acidentes_tratativas_select_all" on public.acidentes_tratativas;
create policy "acidentes_tratativas_select_all"
  on public.acidentes_tratativas for select
  to authenticated using (true);

drop policy if exists "acidentes_tratativas_insert_all" on public.acidentes_tratativas;
create policy "acidentes_tratativas_insert_all"
  on public.acidentes_tratativas for insert
  to authenticated with check (true);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'acidentes',
  'acidentes',
  true,
  52428800,
  array[
    'image/jpeg',
    'image/jpg',
    'image/png',
    'image/webp',
    'image/heic',
    'image/heif',
    'video/mp4',
    'video/quicktime',
    'application/pdf'
  ]
)
on conflict (id) do update
set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "acidentes_storage_select" on storage.objects;
create policy "acidentes_storage_select"
  on storage.objects
  for select
  to anon, authenticated
  using (bucket_id = 'acidentes');

drop policy if exists "acidentes_storage_insert" on storage.objects;
create policy "acidentes_storage_insert"
  on storage.objects
  for insert
  to authenticated
  with check (bucket_id = 'acidentes');

drop policy if exists "acidentes_storage_update" on storage.objects;
create policy "acidentes_storage_update"
  on storage.objects
  for update
  to authenticated
  using (bucket_id = 'acidentes')
  with check (bucket_id = 'acidentes');

notify pgrst, 'reload schema';
